global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3200"]

  - job_name: "grindsense-api"
    static_configs:
      - targets: ["grindsense-api:3000"]
