apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '"traceId":"(\w+)"'
          name: TraceID

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
    jsonData:
      serviceMap:
        datasourceUid: "prometheus"
      nodeGraph:
        enabled: true
      tracesToLogsV2:
        datasourceUid: "loki"
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
        filterByTraceID: true
        filterBySpanID: true
        customQuery: false
        tags:
          - key: "service.name"
            value: "grindsense-api"
      tracesToMetrics:
        datasourceUid: "prometheus"
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
        tags:
          - key: "service.name"
            value: "service"
        queries:
          - name: "Taxa de Requisições (Amostrada)"
            query: 'sum(rate(traces_spanmetrics_latency_count{service="$${__tags.service}"}[5m]))'
